#!/bin/bash
rsync -ar --delete /home/ed/Clouds "/run/media/ed/TOSHIBA EXT"
rsync -ar --delete /home/ed/Musics "/run/media/ed/TOSHIBA EXT/Storage/Linux/Arch Linux/garbage"
rsync -ar --delete /home/ed/Pictures "/run/media/ed/TOSHIBA EXT/Storage/Linux/Arch Linux/garbage"
rsync -ar --delete /home/ed/Documents "/run/media/ed/TOSHIBA EXT/Storage/Linux/Arch Linux/garbage"
rsync -ar --delete /home/ed/Downloads "/run/media/ed/TOSHIBA EXT/Storage/Linux/Arch Linux/garbage"
rsync -ar --delete /home/ed/scripts "/run/media/ed/TOSHIBA EXT/Storage/Linux/Arch Linux/openbox"
rsync -ar --delete /home/ed/bin "/run/media/ed/TOSHIBA EXT/Storage/Linux/Arch Linux/openbox"
rsync -ar --delete /home/ed/Templates "/run/media/ed/TOSHIBA EXT/Storage/Linux/Arch Linux/openbox"
rsync -ar --delete /home/ed/.local "/run/media/ed/TOSHIBA EXT/Storage/Linux/Arch Linux/openbox"
rsync -ar --delete /home/ed/.config "/run/media/ed/TOSHIBA EXT/Storage/Linux/Arch Linux/openbox"
rsync -ar --delete /home/ed/.bashrc "/run/media/ed/TOSHIBA EXT/Storage/Linux/Arch Linux/openbox"
rsync -ar --delete /home/ed/.xprofile "/run/media/ed/TOSHIBA EXT/Storage/Linux/Arch Linux/openbox"
rsync -ar --delete /home/ed/.xinitrc "/run/media/ed/TOSHIBA EXT/Storage/Linux/Arch Linux/openbox"
rsync -ar --delete /home/ed/.fehbg "/run/media/ed/TOSHIBA EXT/Storage/Linux/Arch Linux/openbox"
rsync -ar --delete /home/ed/README.md "/run/media/ed/TOSHIBA EXT/Storage/Linux/Arch Linux/openbox"
read -p "Press ENTER to exit ..."
