#!/bin/bash

clear
echo 'Super+1 >> go to desktop 1		Ctrl+Alt+f >> mozilla Firefox'
echo 'Super+2 >> go to desktop 2		Ctrl+Alt+h >> tHunderbird'
echo 'Super+t >> lxTerminal			Ctrl+Alt+g >> Google chromium'
echo 'Super+p >> Pcmanfm			Ctrl+Alt+b >> douBlecmd'
echo 'Super+g >> Geany			Ctrl+Alt+t >> xTerm'
echo 'Super+i >> Iconify the windows		Ctrl+Alt+k >> sKype'
echo 'Super+m >> Maximize the windows		Ctrl+Alt+l >> teLegramm'
echo 'Super+d >> show Desktop			Ctrl+Alt+v >> Viber'
echo 'Super+o >> shOw root menu		Ctrl+Alt+n >> whatsapp-for-liNux'
echo 'Super+w >> shoW combined menu		Ctrl+Alt+i >> mount google drIve'
echo 'Super+b >> mount usB			Ctrl+Alt+o >> mount Onedrive'
echo 'Super+u >> umount Usb			Ctrl+Alt+r >> Run a command'
echo 'Super+c >> Conky on			Ctrl+Alt+p >> coPy frame'
echo 'Super+k >> Kill conky			Ctrl+Alt+w >> copy Window'
echo 'Super+l >> Lock screen			Ctrl+Alt+s >> copy Screen'
echo 'Super+f >> wtF script'
echo 'Super+n >> recoNfigure openbox		Ctrl+Alt+Del >> Task Manager'
echo 'Super+r >> Rofi				Alt+F4 >> Close the window'
echo 'Super+y >> bpYtop			Alt+Space >> Show Menu'
echo 'Super+q >> Quit the session		Alt+Tab >> Next Window'
echo '					Alt+Sift+Tab >> Previous Window'
